Update pareto.yml

diff --git a/.github/workflows/pareto.yml b/.github/workflows/pareto.yml
--- a/.github/workflows/pareto.yml
+++ b/.github/workflows/pareto.yml
@@ -49,4 +49,18 @@ jobs:
         run: |
           cat issues.json
     
-      - name: Run Pareto analysis ▋
+      - name: Run Pareto analysis script
+        run: |
+          python .github/scripts/pareto.py
+
+      - name: Check if Pareto chart is generated
+        run: |
+          if [ -f "pareto_chart.png" ]; then echo "Pareto chart generated"; else echo "Pareto chart not found"; fi
+
+      - name: Commit and push chart
+        run: |
+          git config --global user.name 'github-actions'
+          git config --global user.email 'github-actions@github.com'
+          git add ishikawa/pareto_chart.png
+          git commit -m 'Update generated Pareto chart' || echo "No changes to commit"
+          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }} || echo "No changes to push"
